check:
  handler: 02_pipeline/check.main
  description: Checks for package on PyPi via the API
  runtime: python3.8
  timeout: 30
  memorySize: 256
  layers:
    - arn:aws:lambda:${self:provider.region}:113088814899:layer:Klayers-python37-packaging:1
    - arn:aws:lambda:${self:provider.region}:770693421928:layer:Klayers-p38-requests:7
    - arn:aws:lambda:${self:provider.region}:017000801446:layer:AWSLambdaPowertoolsPython:6

build:
  handler: 02_pipeline/build.main
  description: Builds the package inside the lambda using pip
  runtime: python3.8
  timeout: 180
  memorySize: 1769
  environment:
    POWERTOOLS_SERVICE_NAME: Klayers.Build
  iamRoleStatementsName: ${self:provider.stage}-build
  iamRoleStatements:
  - Effect: Allow
    Action:
    - s3:PutObject
    - s3:PutObjectAcl
    Resource: ${self:custom.s3LayersArn}/*
  - Effect: Allow
    Action:
    - s3:ListBucket
    Resource: ${self:custom.s3LayersArn}
  - Effect: Allow
    Action:
    - dynamodb:PutItem
    - dynamodb:UpdateItem
    - dynamodb:GetItem
    Resource: ${self:custom.dbArn}
  layers:
    - arn:aws:lambda:${self:provider.region}:553035198032:layer:gcc-lambda2:4  # https://github.com/lambci/gcc-lambda-layer
    - arn:aws:lambda:${self:provider.region}:017000801446:layer:AWSLambdaPowertoolsPython:6


deploy:
  handler: 02_pipeline/deploy.main
  description: Deploys functions to multiple regions
  runtime: python3.8
  timeout: 600
  memorySize: 512
  environment:
    POWERTOOLS_SERVICE_NAME: Klayers.Deploy
    EXPIRY_DAYS: 365
  iamRoleStatementsName: ${self:provider.stage}-deploy
  iamRoleStatements:
    - Effect: Allow
      Action:
      - dynamodb:GetItem
      - dynamodb:PutItem
      - dynamodb:Query
      - dynamodb:UpdateItem
      Resource: 
      - ${self:custom.dbArn}
      - ${self:custom.dbArn}/index/package_global_by_python_version
    - Effect: Allow
      Action:
      - lambda:AddLayerVersionPermission
      - lambda:GetLayerVersion
      Resource: "*"
    - Effect: Allow
      Action:
       - lambda:PublishLayerVersion
      Resource: "*"
    - Effect: Allow
      Action:
      - s3:GetObject
      Resource: ${self:custom.s3LayersArn}/*
  layers:
    - arn:aws:lambda:${self:provider.region}:113088814899:layer:Klayers-python37-packaging:1
    - arn:aws:lambda:${self:provider.region}:017000801446:layer:AWSLambdaPowertoolsPython:6

build39:
  description: Builds the package in a container for python3.9 then uploads to S3
  image: ${ssm:/${self:service}/${self:provider.stage}/build/p39/x86/repo}@${ssm:/${self:service}/${self:provider.stage}/build/p39/x86/digest}
  timeout: 600
  memorySize: 1769  # exactly one vcpu
  iamRoleStatementsName: ${self:provider.stage}-buildp39
  iamRoleStatements:
  - Effect: Allow
    Action:
    - s3:PutObject
    - s3:PutObjectAcl
    Resource: ${self:custom.s3LayersArn}/*
  - Effect: Allow
    Action:
    - s3:ListBucket
    Resource: ${self:custom.s3LayersArn}
  - Effect: Allow
    Action:
    - dynamodb:PutItem
    - dynamodb:UpdateItem
    - dynamodb:GetItem
    Resource: ${self:custom.dbArn}
