cloudfrontdistribution:
  Type: AWS::CloudFront::Distribution
  Properties:
    DistributionConfig:
      Aliases:
      - ${self:custom.apiDomainName}
      Enabled: 'true'
      HttpVersion: http2
      PriceClass: PriceClass_All
      ViewerCertificate:
        AcmCertificateArn: ${self:custom.apiCertArn}
        MinimumProtocolVersion: TLSv1.2_2019
        SslSupportMethod: sni-only
      Origins:
      - Id: ${self:provider.stage}
        DomainName:
          Fn::Join:
          - ''
          - - Ref: HttpApi
            - .execute-api.
            - ${self:provider.region}
            - .amazonaws.com
        CustomOriginConfig:
          HTTPPort: '80'
          HTTPSPort: '443'
          OriginProtocolPolicy: https-only
          OriginSSLProtocols: 
          - TLSv1.2
      DefaultCacheBehavior:
        AllowedMethods:
        - GET
        - HEAD
        CachedMethods:
        - GET
        - HEAD
        TargetOriginId: ${self:provider.stage}
        ForwardedValues:
          QueryString: 'true'
          Cookies:
            Forward: none
        MinTTL: '3600'
        MaxTTL: '86400'
        ViewerProtocolPolicy: https-only
        Compress: True

distributionSSM:
  Type: AWS::SSM::Parameter
  Properties:
    Description: Cloudfront Distribution ID for API
    Name: /${self:custom.appName}/${self:provider.stage}/api/cfDistribution/id
    Tier: Standard
    Type: String
    Value: 
      Ref: cloudfrontdistribution
