check:
  handler: 02_pipeline/check.main
  description: Checks for package on PyPi via the API
  runtime: python3.8
  timeout: 30
  memorySize: 256
  layers:
    - arn:aws:lambda:${self:provider.region}:113088814899:layer:Klayers-python37-packaging:1
    - arn:aws:lambda:${self:provider.region}:770693421928:layer:Klayers-python38-requests:5
    - arn:aws:lambda:${self:provider.region}:770693421928:layer:Klayers-python38-aws-lambda-powertools:23

build:
  handler: 02_pipeline/build.main
  description: Builds the package inside the lambda using pip
  runtime: python3.8
  timeout: 180
  memorySize: 1792
  environment:
    POWERTOOLS_SERVICE_NAME: Klayers.Build
  iamRoleStatementsName: ${self:provider.stage}-build
  iamRoleStatements:
  - Effect: Allow
    Action:
    - s3:PutObject
    - s3:GetObject
    - s3:DeleteObject
    - s3:PutObjectAcl
    - s3:GetObjectAcl
    - s3:AbortMultipartUpload
    Resource: ${self:custom.s3LayersArn}/*
  - Effect: Allow
    Action:
    - s3:ListBucket
    Resource: ${self:custom.s3LayersArn}
  - Effect: Allow
    Action:
    - dynamodb:PutItem
    - dynamodb:Query
    - dynamodb:UpdateItem
    - dynamodb:GetItem
    Resource: ${self:custom.dbArn}
  layers:
    - arn:aws:lambda:${self:provider.region}:770693421928:layer:Klayers-python38-aws-lambda-powertools:23


deploy:
  handler: 02_pipeline/deploy.main
  description: Deploys functions to multiple regions
  runtime: python3.8
  timeout: 600
  memorySize: 512
  environment:
    LAMBDA_PREFIX: ${self:custom.lambdaPrefix}
    POWERTOOLS_SERVICE_NAME: Klayers.Deploy
    EXPIRY_DAYS: 60
  iamRoleStatementsName: ${self:provider.stage}-deploy
  iamRoleStatements:
    - Effect: Allow
      Action:
      - dynamodb:GetItem
      - dynamodb:PutItem
      - dynamodb:Query
      - dynamodb:UpdateItem
      Resource: 
      - ${self:custom.dbArn}
      - ${self:custom.dbArn}/index/package_global
    - Effect: Allow
      Action:
      - lambda:AddLayerVersionPermission
      - lambda:GetLayerVersion
      Resource: "*"
    - Effect: Allow
      Action:
       - lambda:PublishLayerVersion
      Resource: "*"
    - Effect: Allow
      Action:
      - s3:GetObject
      Resource: ${self:custom.s3LayersArn}/*
  layers:
    - arn:aws:lambda:${self:provider.region}:113088814899:layer:Klayers-python37-boto3:2
    - arn:aws:lambda:${self:provider.region}:113088814899:layer:Klayers-python37-packaging:1
    - arn:aws:lambda:${self:provider.region}:770693421928:layer:Klayers-python38-aws-lambda-powertools:23